name: Trigger Release

on:
  # Run every day at 23:15 UTC
  # TODO: Disabled cron for now, but uncomment
  # once replaced the old release workflow.
  # schedule:
  #   - cron: '15 23 * * *'
  # Run manually
  workflow_dispatch:
    inputs:
      releaseType:
        description: Release Type
        required: true
        type: choice
        # Cron job will run canary release
        default: canary
        options:
          - canary
          - stable
          - release-candidate

      force:
        description: Forced Release
        default: false
        type: boolean

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  TURBO_VERSION: 2.5.5
  NODE_LTS_VERSION: 20
  BUN_VERSION: 1.2.20

permissions:
  # To create PR
  pull-requests: write

jobs:
  start:
    if: github.repository_owner == 'kijv'
    runs-on: ubuntu-latest
    environment: release-${{ github.event.inputs.releaseType }}
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_LTS_VERSION }}
          check-latest: true
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}
      
      # Since actions/checkout won't include the latest tag information,
      # use the old clone workflow while still preserving branch specific
      # checkout behavior to support backports.
      # x-ref: https://github.com/vercel/next.js/pull/63167
      - name: Clone repository
        run: git clone https://github.com/kijv/neapolitan.git --depth=25 --single-branch --branch ${GITHUB_REF_NAME:-main} .

      - name: Check token
        run: gh auth status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get commit of the latest tag
        run: echo "LATEST_TAG_COMMIT=$(git rev-list -n 1 $(git describe --tags --abbrev=0))" >> $GITHUB_ENV

      - name: Get latest commit
        run: echo "LATEST_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Check if new commits since last tag
        if: ${{ github.event.inputs.releaseType != 'stable' && github.event.inputs.force != true }}
        run: |
          if [ "$LATEST_TAG_COMMIT" = "$LATEST_COMMIT" ]; then
            echo "No new commits. Exiting..."
            exit 1
          fi

      # https://github.com/actions/virtual-environments/issues/1187
      - name: tune linux network
        run: sudo ethtool -K eth0 tx off rx off

      - run: bun install
      - run: bun run build
        
      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          version: bun run ci:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TYPE: ${{ github.event.inputs.releaseType }}